OrdererOrgs:
  - Name: Orderer
    Domain: orderer.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: Govt
    Domain: govt.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: District
    Domain: district.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Shop
    Domain: shop.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
